# config.yaml

# Paths
model_to_decode_path: /neurospin/dico/data/deep_folding/current/models/Champollion_V1_after_ablation/SFint-SR_right/name08-12-43_252
dataset_folder: /neurospin/dico/data/deep_folding/current/datasets
train_csv: ukb40_random_embeddings/train_embeddings.csv
val_test_csv: ukb40_random_embeddings/val_embeddings.csv
out_dir: runs

# Model / training parameters
num_cpu_workers: 10
batch_size: 32
loss: bce
learning_rate: 5e-4
num_epochs: 5
dropout: 0.05
save_best_model: true

# for train_all_regions.py
model_to_decode_dir: /neurospin/dico/data/deep_folding/current/models/Champollion_V1_after_ablation